language: android

android:
  components:
    - tools
    - platform-tools

    # The BuildTools version used
    - build-tools-30.0.0

    # The SDK version used to compile
    - android-30

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

before_install:
  - yes | sdkmanager "platforms;android-30"

script:
  - ./gradlew ktlint